-- TIMESTAMP
-- THE TIMESTAMP datatype is used for values that contain both date and time parts
-- TIMESTAM FUNCTIONS/OPERATORS---
SHOW TIMEZONE
SELECT NOW()
SELECT TIMEOFDAY()
SELECT CURRENT_TIME
SELECT CURRENT_DATE